-- Add deposit history types
ALTER TYPE "HistoryType" ADD VALUE IF NOT EXISTS 'DEPOSIT_PENDING';
ALTER TYPE "HistoryType" ADD VALUE IF NOT EXISTS 'DEPOSIT_APPROVED';
ALTER TYPE "HistoryType" ADD VALUE IF NOT EXISTS 'DEPOSIT_REJECTED';
